baseURL = 'https://blog.phpguru.net'
languageCode = 'en-us'
title = 'Useful PHP Tricks, Laravel Tips, Tricks and Best Practices'
theme = '2022'
ignoreFiles = ['\assets\node_modules\.*']
[params]
    name = "PHPGuru"
    description = "PHP Tricks, Laravel Tips to Make You a Better Programmer"
    keywords = "PHP Tricks, Laravel Tips"
    dateFormat = "2006-01-02 15:04:05"
    image = "/themes/2022/src/assets/images/logo.png"
    blog_pager = 10
    note_pager = 10
    article_pager = 10
    home_post_limit = 10
    GACode = "G-44831C2LM4"
[taxonomies]
    category = "categories"
    tag = "tags"